export function adicionar(a, b) {
    return a + b;
}

export const events = ["JEEC25", "JEEC24", "JEEC23"];

export const responsibles = ["Toni", "Bárbara", "Nicolau", "Tomás", "Alberto"];

export const days = ["Segunda", "Terça", "Quarta"];

export const tiers = [
    {
      name: "Gold",
      priority: "1",
      cnumber: "5",
      medal: "Yes",
      website: "Yes",
      social: "Yes",
      canvas: "Yes",
      poster: "Yes",
      video: "Yes",
      teaser: "Yes",
      post: "Yes"
    },
    {
      name: "Silver",
      priority: "2",
      cnumber: "5",
      medal: "Yes",
      website: "Yes",
      social: "Yes",
      canvas: "Yes",
      poster: "Yes",
      video: "Yes",
      teaser: "Yes",
      post: "Yes"
    },
    {
      name: "Bronze",
      priority: "3",
      cnumber: "5",
      medal: "Yes",
      website: "Yes",
      social: "Yes",
      canvas: "Yes",
      poster: "Yes",
      video: "Yes",
      teaser: "Yes",
      post: "Yes"
    },
  ];
  

export const companies = [
    {
      id: "1",
      name: "Apple",
      tier: "Gold",
      username: "apple",
      jeec: "Alberto",
      web: "https://www.apple.com",
      email: "1234@apple.com",
      event: "JEEC25",
      cv: "yes",
      password: "TimCook",
      img: "../../assets/wrizz.jpg",
      days: "Segunda"
    },
    {
      id: "2",
      name: "Vibrolândia",
      tier: "Silver",
      username: "vibro",
      jeec: "Tomás",
      web: "https://www.apple.com/",
      email: "geral@vibro.pt",
      event: "JEEC25",
      cv: "no",
      password: "CuDeMelancia",
      img: "../../assets/wrizz.jpg",
      days: "Segunda"
    },
    {
      id: "1",
      name: "Apple",
      tier: "Gold",
      username: "apple",
      jeec: "Alberto",
      web: "https://www.apple.com/",
      email: "1234@apple.com",
      event: "JEEC25",
      cv: "yes",
      password: "TimCook",
      img: "../../assets/wrizz.jpg",
      days: "Segunda"
    },
    {
      id: "2",
      name: "Vibrolândia",
      tier: "Silver",
      username: "vibro",
      jeec: "Tomás",
      web: "https://www.apple.com/",
      email: "geral@vibro.pt",
      event: "JEEC25",
      cv: "no",
      password: "CuDeMelancia",
      img: "../../assets/wrizz.jpg",
      days: "Segunda"
    },
    {
      id: "1",
      name: "Apple",
      tier: "Gold",
      username: "apple",
      jeec: "Alberto",
      web: "https://www.apple.com/",
      email: "1234@apple.com",
      event: "JEEC25",
      cv: "yes",
      password: "TimCook",
      img: "../../assets/wrizz.jpg",
      days: "Segunda"
    },
    {
      id: "2",
      name: "Vibrolândia",
      tier: "Silver",
      username: "vibro",
      jeec: "Tomás",
      web: "https://www.apple.com/",
      email: "geral@vibro.pt",
      event: "JEEC25",
      cv: "no",
      password: "CuDeMelancia",
      img: "../../assets/wrizz.jpg",
      days: "Segunda"
    },
    {
      id: "1",
      name: "Apple",
      tier: "Gold",
      username: "apple",
      jeec: "Alberto",
      web: "https://www.apple.com/",
      email: "1234@apple.com",
      event: "JEEC24",
      cv: "yes",
      password: "TimCook",
      img: "../../assets/wrizz.jpg",
      days: "Segunda"
    },
    {
      id: "2",
      name: "Vibrolândia",
      tier: "Silver",
      username: "vibro",
      jeec: "Tomás",
      web: "https://www.apple.com/",
      email: "geral@vibro.pt",
      event: "JEEC24",
      cv: "no",
      password: "CuDeMelancia",
      img: "../../assets/wrizz.jpg",
      days: "Segunda"
    },
    {
      id: "1",
      name: "Apple",
      tier: "Gold",
      username: "apple",
      jeec: "Alberto",
      web: "https://www.apple.com/",
      email: "1234@apple.com",
      event: "JEEC25",
      cv: "yes",
      password: "TimCook",
      img: "../../assets/wrizz.jpg",
      days: "Segunda"
    },
    {
      id: "2",
      name: "Vibrolândia",
      tier: "Silver",
      username: "vibro",
      jeec: "Tomás",
      web: "https://www.apple.com/",
      email: "geral@vibro.pt",
      event: "JEEC25",
      cv: "no",
      password: "CuDeMelancia",
      img: "../../assets/wrizz.jpg",
      days: "Segunda"
    },
    {
      id: "1",
      name: "Apple",
      tier: "Gold",
      username: "apple",
      jeec: "Alberto",
      web: "https://www.apple.com/",
      email: "1234@apple.com",
      event: "JEEC25",
      cv: "yes",
      password: "TimCook",
      img: "../../assets/wrizz.jpg",
      days: "Segunda"
    },
    {
      id: "2",
      name: "Vibrolândia",
      tier: "Silver",
      username: "vibro",
      jeec: "Tomás",
      web: "https://www.apple.com/",
      email: "geral@vibro.pt",
      event: "JEEC25",
      cv: "no",
      password: "CuDeMelancia",
      img: "../../assets/wrizz.jpg",
      days: "Segunda"
    },
    {
      id: "1",
      name: "Apple",
      tier: "Gold",
      username: "apple",
      jeec: "Alberto",
      web: "https://www.apple.com",
      email: "1234@apple.com",
      event: "JEEC25",
      cv: "yes",
      password: "TimCook",
      img: "../../assets/wrizz.jpg",
      days: "Segunda"
    },
    {
      id: "2",
      name: "Vibrolândia",
      tier: "Silver",
      username: "vibro",
      jeec: "Tomás",
      web: "https://www.apple.com/",
      email: "geral@vibro.pt",
      event: "JEEC25",
      cv: "no",
      password: "CuDeMelancia",
      img: "../../assets/wrizz.jpg",
      days: "Segunda"
    },
    {
      id: "1",
      name: "Apple",
      tier: "Gold",
      username: "apple",
      jeec: "Alberto",
      web: "https://www.apple.com/",
      email: "1234@apple.com",
      event: "JEEC25",
      cv: "yes",
      password: "TimCook",
      img: "../../assets/wrizz.jpg",
      days: "Segunda"
    },
    {
      id: "2",
      name: "Vibrolândia",
      tier: "Silver",
      username: "vibro",
      jeec: "Tomás",
      web: "https://www.apple.com/",
      email: "geral@vibro.pt",
      event: "JEEC25",
      cv: "no",
      password: "CuDeMelancia",
      img: "../../assets/wrizz.jpg",
      days: "Segunda"
    },
    {
      id: "1",
      name: "Apple",
      tier: "Gold",
      username: "apple",
      jeec: "Alberto",
      web: "https://www.apple.com/",
      email: "1234@apple.com",
      event: "JEEC25",
      cv: "yes",
      password: "TimCook",
      img: "../../assets/wrizz.jpg",
      days: "Segunda"
    },
    {
      id: "2",
      name: "Vibrolândia",
      tier: "Silver",
      username: "vibro",
      jeec: "Tomás",
      web: "https://www.apple.com/",
      email: "geral@vibro.pt",
      event: "JEEC25",
      cv: "no",
      password: "CuDeMelancia",
      img: "../../assets/wrizz.jpg",
      days: "Segunda"
    },
    {
      id: "1",
      name: "Apple",
      tier: "Gold",
      username: "apple",
      jeec: "Alberto",
      web: "https://www.apple.com/",
      email: "1234@apple.com",
      event: "JEEC24",
      cv: "yes",
      password: "TimCook",
      img: "../../assets/wrizz.jpg",
      days: "Segunda"
    },
    {
      id: "2",
      name: "Vibrolândia",
      tier: "Silver",
      username: "vibro",
      jeec: "Tomás",
      web: "https://www.apple.com/",
      email: "geral@vibro.pt",
      event: "JEEC24",
      cv: "no",
      password: "CuDeMelancia",
      img: "../../assets/wrizz.jpg",
      days: "Segunda"
    },
    {
      id: "1",
      name: "Apple",
      tier: "Gold",
      username: "apple",
      jeec: "Alberto",
      web: "https://www.apple.com/",
      email: "1234@apple.com",
      event: "JEEC25",
      cv: "yes",
      password: "TimCook",
      img: "../../assets/wrizz.jpg",
      days: "Segunda"
    },
    {
      id: "2",
      name: "Vibrolândia",
      tier: "Silver",
      username: "vibro",
      jeec: "Tomás",
      web: "https://www.apple.com/",
      email: "geral@vibro.pt",
      event: "JEEC25",
      cv: "no",
      password: "CuDeMelancia",
      img: "../../assets/wrizz.jpg",
      days: "Segunda"
    },
    {
      id: "1",
      name: "Apple",
      tier: "Gold",
      username: "apple",
      jeec: "Alberto",
      web: "https://www.apple.com/",
      email: "1234@apple.com",
      event: "JEEC25",
      cv: "yes",
      password: "TimCook",
      img: "../../assets/wrizz.jpg",
      days: "Segunda"
    },
    {
      id: "2",
      name: "Vibrolândia",
      tier: "Silver",
      username: "vibro",
      jeec: "Tomás",
      web: "https://www.apple.com/",
      email: "geral@vibro.pt",
      event: "JEEC25",
      cv: "no",
      password: "CuDeMelancia",
      img: "../../assets/wrizz.jpg",
      days: "Segunda"
    },
  ];